import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { ArrowUpRight, CheckCircle2, FileText, Lightbulb, Sparkles, Trash2, Upload } from 'lucide-react';
import Alert from '../../components/ui/Alert';
import Badge from '../../components/ui/Badge';
import Button from '../../components/ui/Button';
import Card, { CardHeader } from '../../components/ui/Card';
import Input from '../../components/ui/Input';
import LoadingSpinner from '../../components/common/LoadingSpinner';
import ProgressBar from '../../components/ui/ProgressBar';
import Textarea from '../../components/ui/Textarea';
import { formatDate } from '../../utils';
import {
  clearResumeError,
  clearResumeSuccess,
  fetchResumeAnalyses,
  fetchResumeAnalysis,
  removeResumeAnalysis,
  submitResumeAnalysis,
} from '../../store/slices/resumeSlice';

const MAX_FILE_BYTES = 4 * 1024 * 1024;

const ResumeAnalysisResults = ({ analysis }) => {
  if (!analysis) return null;
  const report = analysis.analysis;
  return (
    <div className="space-y-5">
      <Card>
        <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <Badge variant="cyan">Resume review</Badge>
            <Badge variant={analysis.analysisSource === 'rule_based' ? 'warning' : 'success'} className="ml-2">
              {analysis.analysisSource === 'rule_based' ? 'Checklist fallback · not AI' : 'AI review'}
            </Badge>
            <h3 className="mt-3 text-xl font-bold text-text-main">{analysis.fileName}</h3>
            <p className="mt-1 text-sm text-text-secondary">
              {analysis.targetRole ? `Target role: ${analysis.targetRole} · ` : ''}{analysis.wordCount} words · {formatDate(analysis.analyzedAt)}
            </p>
            {analysis.analysisSource === 'rule_based' && <div role="status" className="mt-3 rounded-lg border border-warning/30 bg-warning/10 px-3 py-2 text-sm text-text-secondary">{analysis.notice || 'This older saved result was generated by a checklist and is not AI analysis. Upload the resume again after Gemini quota is available for a proper AI review.'}</div>}
            <p className="mt-3 max-w-2xl text-sm leading-6 text-text-secondary">{report.summary}</p>
          </div>
          <div className="shrink-0 text-center">
            {analysis.analysisSource === 'rule_based' ? <p className="text-sm font-semibold text-warning">No AI score</p> : <>
              <p className="text-4xl font-bold text-primary">{report.overallScore}</p>
              <p className="text-xs text-text-secondary">content score / 100</p>
            </>}
          </div>
        </div>
        {analysis.analysisSource !== 'rule_based' && <>
          <div className="mt-5"><ProgressBar value={report.overallScore} /></div>
          <p className="mt-3 text-xs text-text-secondary">This score reflects resume content quality and is not a hiring probability or guarantee.</p>
        </>}
      </Card>

      <div className="grid gap-5 lg:grid-cols-2">
        <Card>
          <CardHeader title="Section review" subtitle="Evidence-based feedback for the sections in your resume." />
          <div className="space-y-3">
            {report.sectionReviews.map((section) => (
              <div key={section.section} className="rounded-xl border border-border p-4">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <h4 className="font-semibold text-text-main">{section.section}</h4>
                  <Badge variant={section.status === 'strong' ? 'success' : section.status === 'missing' ? 'warning' : 'outline'}>
                    {analysis.analysisSource === 'rule_based' ? section.status.replace('_', ' ') : `${section.status.replace('_', ' ')} · ${section.score}%`}
                  </Badge>
                </div>
                <p className="mt-2 text-sm leading-6 text-text-secondary">{section.feedback}</p>
              </div>
            ))}
          </div>
        </Card>
        <div className="space-y-5">
          <Card>
            <CardHeader title="What is working" />
            {report.strengths.length ? <ul className="space-y-2">{report.strengths.map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-text-secondary"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-success" />{item}</li>)}</ul> : <p className="text-sm text-text-secondary">No strengths were identified in this review.</p>}
          </Card>
          <Card>
            <CardHeader title="Prioritized improvements" />
            <ol className="list-decimal space-y-2 pl-5 text-sm leading-6 text-text-secondary">{report.improvements.map((item) => <li key={item}>{item}</li>)}</ol>
          </Card>
          {report.missingKeywords.length > 0 && (
            <Card>
              <CardHeader title="Relevant keywords to consider" subtitle="Only include terms that accurately describe your experience." />
              <div className="flex flex-wrap gap-2">{report.missingKeywords.map((keyword) => <Badge key={keyword}>{keyword}</Badge>)}</div>
            </Card>
          )}
        </div>
      </div>
      <Card>
        <CardHeader title="Your next steps" />
        <ol className="grid gap-3 sm:grid-cols-2">{report.actionPlan.map((item, index) => <li key={item} className="flex gap-3 rounded-xl bg-background p-4 text-sm leading-6 text-text-secondary"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary-light font-semibold text-primary">{index + 1}</span>{item}</li>)}</ol>
      </Card>
    </div>
  );
};

const ResumePage = () => {
  const dispatch = useDispatch();
  const { profile } = useSelector((state) => state.user);
  const { analyses, currentAnalysis, hasLoaded, loading, analyzing, loadingAnalysis, deleting, error, success } = useSelector((state) => state.resume);
  const [resumeText, setResumeText] = useState('');
  const [targetRole, setTargetRole] = useState('');
  const [file, setFile] = useState(null);
  const [formError, setFormError] = useState('');

  useEffect(() => {
    if (!hasLoaded) dispatch(fetchResumeAnalyses());
  }, [dispatch, hasLoaded]);

  const onChooseFile = (event) => {
    const selected = event.target.files?.[0] || null;
    setFormError('');
    if (selected && selected.size > MAX_FILE_BYTES) {
      setFile(null);
      setFormError('Choose a file smaller than 4 MB.');
      event.target.value = '';
      return;
    }
    if (selected && !/\.(pdf|txt)$/i.test(selected.name)) {
      setFile(null);
      setFormError('Upload a PDF or UTF-8 text file.');
      event.target.value = '';
      return;
    }
    setFile(selected);
    if (selected) setResumeText('');
  };

  const onSubmit = async (event) => {
    event.preventDefault();
    setFormError('');
    if (!file && resumeText.trim().length < 100) {
      setFormError('Paste at least 100 characters of resume text, or choose a PDF or text file.');
      return;
    }
    const action = await dispatch(submitResumeAnalysis({ resumeText, targetRole, file }));
    if (submitResumeAnalysis.fulfilled.match(action)) {
      setResumeText('');
      setFile(null);
      const input = document.getElementById('resume-file');
      if (input) input.value = '';
    }
  };

  const handleDelete = (resumeId) => {
    if (window.confirm('Delete this saved resume analysis? The original resume file is not stored.')) {
      dispatch(removeResumeAnalysis(resumeId));
    }
  };

  if (loading && !hasLoaded) return <LoadingSpinner message="Loading your resume reviews..." />;

  return (
    <div className="mx-auto max-w-6xl space-y-6">
      <header>
        <p className="text-sm font-semibold uppercase tracking-wide text-primary">Career documents</p>
        <h2 className="mt-1 text-3xl font-bold text-text-main">Resume Analyzer</h2>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-text-secondary">Get structured feedback on resume clarity, evidence, role relevance, and concrete improvements. Upload a searchable PDF or text file, or paste your resume.</p>
      </header>

      {error && <Alert message={error} onClose={() => dispatch(clearResumeError())} />}
      {formError && <Alert type="warning" message={formError} />}
      {success && <Alert type="success" message={success} onClose={() => dispatch(clearResumeSuccess())} />}

      <Card>
        <CardHeader title="Start a resume review" subtitle="Resume text is sent to the configured AI provider for analysis. The original file is not saved by NextStep AI; only the structured feedback is stored in your account." />
        <form onSubmit={onSubmit} className="space-y-5" aria-busy={analyzing}>
          <Input
            label="Target role (optional)"
            placeholder="For example, Data Analyst"
            value={targetRole}
            maxLength={120}
            onChange={(event) => setTargetRole(event.target.value)}
            autoComplete="organization-title"
          />
          {profile?.careerGoals?.targetJobRole && !targetRole && (
            <button type="button" onClick={() => setTargetRole(profile.careerGoals.targetJobRole)} className="-mt-3 text-left text-xs text-primary hover:underline">
              Use profile goal: {profile.careerGoals.targetJobRole}
            </button>
          )}
          <div className="grid gap-5 lg:grid-cols-2">
            <div>
              <label htmlFor="resume-file" className="text-sm font-medium text-text-main">Upload PDF or text file</label>
              <label htmlFor="resume-file" className="mt-1 flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-border bg-background p-5 text-center transition-colors hover:border-primary focus-within:ring-2 focus-within:ring-primary">
                <Upload className="h-6 w-6 text-primary" aria-hidden="true" />
                <span className="mt-2 text-sm font-medium text-text-main">{file?.name || 'Choose a file'}</span>
                <span className="mt-1 text-xs text-text-secondary">Searchable PDF or UTF-8 TXT · up to 4 MB</span>
                <input id="resume-file" type="file" accept=".pdf,.txt,application/pdf,text/plain" onChange={onChooseFile} className="sr-only" />
              </label>
              {file && <button type="button" onClick={() => { setFile(null); document.getElementById('resume-file').value = ''; }} className="mt-2 text-xs text-primary hover:underline">Remove selected file</button>}
            </div>
            <Textarea
              label="Or paste resume text"
              placeholder="Paste the text from your resume here..."
              rows={6}
              maxLength={20000}
              value={resumeText}
              disabled={Boolean(file)}
              onChange={(event) => setResumeText(event.target.value)}
            />
          </div>
          <div className="flex flex-col gap-3 border-t border-border pt-4 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-xs text-text-secondary">Review may take up to a minute. Avoid including information you do not want analyzed.</p>
            <Button type="submit" loading={analyzing} disabled={analyzing}>
              <Sparkles className="h-4 w-4" aria-hidden="true" /> Analyze resume
            </Button>
          </div>
        </form>
      </Card>

      {loadingAnalysis ? <LoadingSpinner message="Loading saved analysis..." /> : currentAnalysis ? (
        <ResumeAnalysisResults analysis={currentAnalysis} />
      ) : (
        <Card className="py-8 text-center">
          <FileText className="mx-auto h-8 w-8 text-primary" aria-hidden="true" />
          <h3 className="mt-3 text-lg font-semibold text-text-main">Your resume feedback will appear here</h3>
          <p className="mt-1 text-sm text-text-secondary">Add resume text or a supported file to receive a detailed, role-aware review.</p>
        </Card>
      )}

      <section aria-labelledby="resume-history-title" className="space-y-3">
        <div>
          <h3 id="resume-history-title" className="text-xl font-bold text-text-main">Saved reviews</h3>
          <p className="mt-1 text-sm text-text-secondary">Your latest 20 analysis summaries are private to your account.</p>
        </div>
        {analyses.length ? analyses.map((item) => (
          <Card key={item.id} className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div className="min-w-0">
              <h4 className="truncate font-semibold text-text-main">{item.fileName}</h4>
              <p className="mt-1 text-sm text-text-secondary">{item.analysisSource === 'rule_based' ? 'Checklist fallback · not AI' : item.targetRole || 'General review'} · {item.analysisSource === 'rule_based' ? 'AI quota reached' : `${item.analysis.overallScore}/100`} · {formatDate(item.analyzedAt)}</p>
            </div>
            <div className="flex items-center gap-2">
              <Button size="sm" variant="outline" onClick={() => dispatch(fetchResumeAnalysis(item.id))}>
                <ArrowUpRight className="h-4 w-4" aria-hidden="true" /> View review
              </Button>
              <Button size="sm" variant="ghost" disabled={deleting} onClick={() => handleDelete(item.id)} aria-label={`Delete ${item.fileName} analysis`}>
                <Trash2 className="h-4 w-4" aria-hidden="true" />
              </Button>
            </div>
          </Card>
        )) : (
          <Card className="py-5 text-center text-sm text-text-secondary">No saved resume reviews yet. Analyze one to build your history.</Card>
        )}
      </section>
      <div className="flex items-start gap-3 rounded-xl border border-primary/15 bg-primary-light/40 p-4 text-sm text-text-secondary">
        <Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-primary" aria-hidden="true" />
        <p>Use this feedback as editing guidance. Verify every suggestion and include only accurate skills and achievements.</p>
      </div>
    </div>
  );
};

export default ResumePage;
